// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.fabric;

import com.equinix.pulumi.fabric.inputs.RouteAggregationProjectArgs;
import com.equinix.pulumi.fabric.inputs.RouteAggregationTimeoutsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RouteAggregationArgs extends com.pulumi.resources.ResourceArgs {

    public static final RouteAggregationArgs Empty = new RouteAggregationArgs();

    /**
     * Customer-provided route aggregation description
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Customer-provided route aggregation description
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Customer provided name of the route aggregation
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Customer provided name of the route aggregation
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Equinix Project attribute object
     * 
     */
    @Import(name="project", required=true)
    private Output<RouteAggregationProjectArgs> project;

    /**
     * @return Equinix Project attribute object
     * 
     */
    public Output<RouteAggregationProjectArgs> project() {
        return this.project;
    }

    @Import(name="timeouts")
    private @Nullable Output<RouteAggregationTimeoutsArgs> timeouts;

    public Optional<Output<RouteAggregationTimeoutsArgs>> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    /**
     * Equinix defined Route Aggregation Type; BGP*IPv4*PREFIX*AGGREGATION, BGP*IPv6*PREFIX*AGGREGATION
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return Equinix defined Route Aggregation Type; BGP*IPv4*PREFIX*AGGREGATION, BGP*IPv6*PREFIX*AGGREGATION
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private RouteAggregationArgs() {}

    private RouteAggregationArgs(RouteAggregationArgs $) {
        this.description = $.description;
        this.name = $.name;
        this.project = $.project;
        this.timeouts = $.timeouts;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RouteAggregationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RouteAggregationArgs $;

        public Builder() {
            $ = new RouteAggregationArgs();
        }

        public Builder(RouteAggregationArgs defaults) {
            $ = new RouteAggregationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description Customer-provided route aggregation description
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Customer-provided route aggregation description
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param name Customer provided name of the route aggregation
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Customer provided name of the route aggregation
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param project Equinix Project attribute object
         * 
         * @return builder
         * 
         */
        public Builder project(Output<RouteAggregationProjectArgs> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project Equinix Project attribute object
         * 
         * @return builder
         * 
         */
        public Builder project(RouteAggregationProjectArgs project) {
            return project(Output.of(project));
        }

        public Builder timeouts(@Nullable Output<RouteAggregationTimeoutsArgs> timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public Builder timeouts(RouteAggregationTimeoutsArgs timeouts) {
            return timeouts(Output.of(timeouts));
        }

        /**
         * @param type Equinix defined Route Aggregation Type; BGP*IPv4*PREFIX*AGGREGATION, BGP*IPv6*PREFIX*AGGREGATION
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Equinix defined Route Aggregation Type; BGP*IPv4*PREFIX*AGGREGATION, BGP*IPv6*PREFIX*AGGREGATION
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public RouteAggregationArgs build() {
            if ($.project == null) {
                throw new MissingRequiredPropertyException("RouteAggregationArgs", "project");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("RouteAggregationArgs", "type");
            }
            return $;
        }
    }

}
