template: external-bridged-provider
provider: equinix
organization: equinix
upstreamProviderOrg: equinix
providerDefaultBranch: main
major-version: 0
pulumiConvert: 1
testMasterAndReleaseWorkflows: false
publish:
    cdn: false
registryDocs: true
publishRegistry: false
clean-github-workflows: false
plugins:
    - name: random
      version: "4.14.0"
    - name: terraform
      version: "1.0.16"
      kind: converter
    - name: tls
      version: "4.11.0"
# override default env to avoid bringing in
# pulumi-internal environment variables
env:
  TF_APPEND_USER_AGENT: pulumi
# TEMP(?): override default tool versions to
# stay closer to what we used prior to ci-mgmt
toolVersions:
  dotnet: "6.0.x"
  go: "1.23.x"
  java: "11"
  gradle: "7.6"
  nodejs: "22.13.1"
  python: "3.11.8"