# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2

archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-equinix
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    hooks:
      post:
      - env GOOS={{ .Os }} GOARCH={{ .Arch }} go clean -cache
      - env GOOS={{ .Os }} GOARCH={{ .Arch }} go clean -modcache
    ignore: []
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/equinix/pulumi-equinix/provider/pkg/version.Version={{.Tag }}
      - -X github.com/equinix/terraform-provider-equinix/version.ProviderVersion|={{.Tag}}
    main: ./cmd/pulumi-resource-equinix/
changelog:
  disable: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'