// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Fabric
{
    /// <summary>
    /// Fabric V4 API compatible resource allows creation and management of Equinix Fabric Stream Subscriptions
    /// 
    /// Additional Documentation:
    /// * Getting Started: https://docs.equinix.com/observability/streaming-data/integratewithsink/
    /// * API: https://docs.equinix.com/api-catalog/fabricv4/#tag/Stream-Subscriptions
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Equinix = Pulumi.Equinix;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var SPLUNK = new Equinix.Fabric.StreamSubscription("SPLUNK", new()
    ///     {
    ///         Type = "STREAM_SUBSCRIPTION",
    ///         Name = "&lt;name&gt;",
    ///         Description = "&lt;description&gt;",
    ///         StreamId = "&lt;stream_id&gt;",
    ///         Enabled = true,
    ///         EventSelector = new Equinix.Fabric.Inputs.StreamSubscriptionEventSelectorArgs
    ///         {
    ///             Includes = new[]
    ///             {
    ///                 "equinix.fabric.connection.*",
    ///             },
    ///         },
    ///         MetricSelector = new Equinix.Fabric.Inputs.StreamSubscriptionMetricSelectorArgs
    ///         {
    ///             Includes = new[]
    ///             {
    ///                 "equinix.fabric.connection.*",
    ///             },
    ///         },
    ///         Sink = new Equinix.Fabric.Inputs.StreamSubscriptionSinkArgs
    ///         {
    ///             Type = "SPLUNK_HEC",
    ///             Uri = "&lt;splunk_uri&gt;",
    ///             Settings = new Equinix.Fabric.Inputs.StreamSubscriptionSinkSettingsArgs
    ///             {
    ///                 EventIndex = "&lt;splunk_event_index&gt;",
    ///                 MetricIndex = "&lt;splunk_metric_index&gt;",
    ///                 Source = "&lt;splunk_source&gt;",
    ///             },
    ///             Credential = new Equinix.Fabric.Inputs.StreamSubscriptionSinkCredentialArgs
    ///             {
    ///                 Type = "ACCESS_TOKEN",
    ///                 AccessToken = "&lt;splunk_access_token&gt;",
    ///             },
    ///         },
    ///     });
    /// 
    ///     var SLACK = new Equinix.Fabric.StreamSubscription("SLACK", new()
    ///     {
    ///         Type = "STREAM_SUBSCRIPTION",
    ///         Name = "&lt;name&gt;",
    ///         Description = "&lt;description&gt;",
    ///         StreamId = "&lt;stream_id&gt;",
    ///         Enabled = true,
    ///         Sink = new Equinix.Fabric.Inputs.StreamSubscriptionSinkArgs
    ///         {
    ///             Type = "SLACK",
    ///             Uri = "&lt;slack_uri&gt;",
    ///         },
    ///     });
    /// 
    ///     var PAGER_DUTY = new Equinix.Fabric.StreamSubscription("PAGER_DUTY", new()
    ///     {
    ///         Type = "STREAM_SUBSCRIPTION",
    ///         Name = "&lt;name&gt;",
    ///         Description = "&lt;description&gt;",
    ///         StreamId = "&lt;stream_id&gt;",
    ///         Enabled = true,
    ///         Sink = new Equinix.Fabric.Inputs.StreamSubscriptionSinkArgs
    ///         {
    ///             Type = "PAGERDUTY",
    ///             Host = "&lt;pager_duty_host",
    ///             Settings = new Equinix.Fabric.Inputs.StreamSubscriptionSinkSettingsArgs
    ///             {
    ///                 ChangeUri = "&lt;pager_duty_change_uri&gt;",
    ///                 AlertUri = "&lt;pager_duty_alert_uri&gt;",
    ///             },
    ///             Credential = new Equinix.Fabric.Inputs.StreamSubscriptionSinkCredentialArgs
    ///             {
    ///                 Type = "INTEGRATION_KEY",
    ///                 IntegrationKey = "&lt;pager_duty_integration_key&gt;",
    ///             },
    ///         },
    ///     });
    /// 
    ///     var DATADOG = new Equinix.Fabric.StreamSubscription("DATADOG", new()
    ///     {
    ///         Type = "STREAM_SUBSCRIPTION",
    ///         Name = "&lt;name&gt;",
    ///         Description = "&lt;description&gt;",
    ///         StreamId = "&lt;stream_id&gt;",
    ///         Enabled = true,
    ///         Sink = new Equinix.Fabric.Inputs.StreamSubscriptionSinkArgs
    ///         {
    ///             Type = "DATADOG",
    ///             Host = "&lt;datadog_host&gt;",
    ///             Settings = new Equinix.Fabric.Inputs.StreamSubscriptionSinkSettingsArgs
    ///             {
    ///                 Source = "Equinix",
    ///                 ApplicationKey = "&lt;datadog_application_key&gt;",
    ///                 EventUri = "&lt;datadog_event_uri&gt;",
    ///                 MetricUri = "&lt;datadog_metric_uri&gt;",
    ///             },
    ///             Credential = new Equinix.Fabric.Inputs.StreamSubscriptionSinkCredentialArgs
    ///             {
    ///                 Type = "API_KEY",
    ///                 ApiKey = "&lt;datadog_api_key&gt;",
    ///             },
    ///         },
    ///     });
    /// 
    ///     var MSTEAMS = new Equinix.Fabric.StreamSubscription("MSTEAMS", new()
    ///     {
    ///         Type = "STREAM_SUBSCRIPTION",
    ///         Name = "&lt;name&gt;",
    ///         Description = "&lt;description&gt;",
    ///         StreamId = "&lt;stream_id&gt;",
    ///         Enabled = true,
    ///         Sink = new Equinix.Fabric.Inputs.StreamSubscriptionSinkArgs
    ///         {
    ///             Type = "TEAMS",
    ///             Uri = "&lt;msteams_uri&gt;",
    ///         },
    ///     });
    /// 
    ///     var servicenow = new Equinix.Fabric.StreamSubscription("servicenow", new()
    ///     {
    ///         Type = "STREAM_SUBSCRIPTION",
    ///         Name = "&lt;name&gt;",
    ///         Description = "&lt;description&gt;",
    ///         StreamId = "&lt;stream_id&gt;",
    ///         Enabled = true,
    ///         Sink = new Equinix.Fabric.Inputs.StreamSubscriptionSinkArgs
    ///         {
    ///             Type = "SERVICENOW",
    ///             Host = "&lt;servicenow_host&gt;",
    ///             Settings = new Equinix.Fabric.Inputs.StreamSubscriptionSinkSettingsArgs
    ///             {
    ///                 Source = "Equinix",
    ///             },
    ///             Credential = new Equinix.Fabric.Inputs.StreamSubscriptionSinkCredentialArgs
    ///             {
    ///                 Type = "USERNAME_PASSWORD",
    ///                 Username = "&lt;servicenow_username&gt;",
    ///                 Password = "&lt;servicenow_password&gt;",
    ///             },
    ///         },
    ///     });
    /// 
    ///     var webhook = new Equinix.Fabric.StreamSubscription("webhook", new()
    ///     {
    ///         Type = "STREAM_SUBSCRIPTION",
    ///         Name = "&lt;name&gt;",
    ///         Description = "&lt;description&gt;",
    ///         StreamId = "&lt;stream_id&gt;",
    ///         Enabled = true,
    ///         Sink = new Equinix.Fabric.Inputs.StreamSubscriptionSinkArgs
    ///         {
    ///             Type = "WEBHOOK",
    ///             Settings = new Equinix.Fabric.Inputs.StreamSubscriptionSinkSettingsArgs
    ///             {
    ///                 Format = "&lt;webhook_format&gt;",
    ///                 EventUri = "&lt;webhook_event_uri&gt;",
    ///                 MetricUri = "&lt;webhook_metric_uri&gt;",
    ///             },
    ///         },
    ///     });
    /// 
    ///     var grafana = new Equinix.Fabric.StreamSubscription("grafana", new()
    ///     {
    ///         Type = "STREAM_SUBSCRIPTION",
    ///         Name = "&lt;name&gt;",
    ///         Description = "&lt;description&gt;",
    ///         StreamId = "&lt;stream_id&gt;",
    ///         Enabled = true,
    ///         Sink = new Equinix.Fabric.Inputs.StreamSubscriptionSinkArgs
    ///         {
    ///             Type = "WEBHOOK",
    ///             Settings = new Equinix.Fabric.Inputs.StreamSubscriptionSinkSettingsArgs
    ///             {
    ///                 Format = "OPENTELEMETRY",
    ///                 EventUri = "&lt;grafana_event_uri&gt;",
    ///                 MetricUri = "&lt;grafana_metric_uri&gt;",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [EquinixResourceType("equinix:fabric/streamSubscription:StreamSubscription")]
    public partial class StreamSubscription : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Details of the last change on the stream resource
        /// </summary>
        [Output("changeLog")]
        public Output<Outputs.StreamSubscriptionChangeLog> ChangeLog { get; private set; } = null!;

        /// <summary>
        /// Customer-provided stream subscription description
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Stream subscription enabled status
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// Lists of events to be included/excluded on the stream subscription
        /// </summary>
        [Output("eventSelector")]
        public Output<Outputs.StreamSubscriptionEventSelector> EventSelector { get; private set; } = null!;

        /// <summary>
        /// Equinix assigned URI of the stream subscription resource
        /// </summary>
        [Output("href")]
        public Output<string> Href { get; private set; } = null!;

        /// <summary>
        /// Lists of metrics to be included/excluded on the stream subscription
        /// </summary>
        [Output("metricSelector")]
        public Output<Outputs.StreamSubscriptionMetricSelector> MetricSelector { get; private set; } = null!;

        /// <summary>
        /// Customer-provided stream subscription name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The details of the subscriber to the Equinix Stream
        /// </summary>
        [Output("sink")]
        public Output<Outputs.StreamSubscriptionSink> Sink { get; private set; } = null!;

        /// <summary>
        /// Value representing provisioning status for the stream resource
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// The uuid of the stream that is the target of the stream subscription
        /// </summary>
        [Output("streamId")]
        public Output<string> StreamId { get; private set; } = null!;

        [Output("timeouts")]
        public Output<Outputs.StreamSubscriptionTimeouts?> Timeouts { get; private set; } = null!;

        /// <summary>
        /// Type of the stream subscription request
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// Equinix assigned unique identifier of the stream subscription resource
        /// </summary>
        [Output("uuid")]
        public Output<string> Uuid { get; private set; } = null!;


        /// <summary>
        /// Create a StreamSubscription resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StreamSubscription(string name, StreamSubscriptionArgs args, CustomResourceOptions? options = null)
            : base("equinix:fabric/streamSubscription:StreamSubscription", name, args ?? new StreamSubscriptionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private StreamSubscription(string name, Input<string> id, StreamSubscriptionState? state = null, CustomResourceOptions? options = null)
            : base("equinix:fabric/streamSubscription:StreamSubscription", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/equinix",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing StreamSubscription resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static StreamSubscription Get(string name, Input<string> id, StreamSubscriptionState? state = null, CustomResourceOptions? options = null)
        {
            return new StreamSubscription(name, id, state, options);
        }
    }

    public sealed class StreamSubscriptionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Customer-provided stream subscription description
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Stream subscription enabled status
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Lists of events to be included/excluded on the stream subscription
        /// </summary>
        [Input("eventSelector")]
        public Input<Inputs.StreamSubscriptionEventSelectorArgs>? EventSelector { get; set; }

        /// <summary>
        /// Lists of metrics to be included/excluded on the stream subscription
        /// </summary>
        [Input("metricSelector")]
        public Input<Inputs.StreamSubscriptionMetricSelectorArgs>? MetricSelector { get; set; }

        /// <summary>
        /// Customer-provided stream subscription name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The details of the subscriber to the Equinix Stream
        /// </summary>
        [Input("sink", required: true)]
        public Input<Inputs.StreamSubscriptionSinkArgs> Sink { get; set; } = null!;

        /// <summary>
        /// The uuid of the stream that is the target of the stream subscription
        /// </summary>
        [Input("streamId", required: true)]
        public Input<string> StreamId { get; set; } = null!;

        [Input("timeouts")]
        public Input<Inputs.StreamSubscriptionTimeoutsArgs>? Timeouts { get; set; }

        /// <summary>
        /// Type of the stream subscription request
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public StreamSubscriptionArgs()
        {
        }
        public static new StreamSubscriptionArgs Empty => new StreamSubscriptionArgs();
    }

    public sealed class StreamSubscriptionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Details of the last change on the stream resource
        /// </summary>
        [Input("changeLog")]
        public Input<Inputs.StreamSubscriptionChangeLogGetArgs>? ChangeLog { get; set; }

        /// <summary>
        /// Customer-provided stream subscription description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Stream subscription enabled status
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Lists of events to be included/excluded on the stream subscription
        /// </summary>
        [Input("eventSelector")]
        public Input<Inputs.StreamSubscriptionEventSelectorGetArgs>? EventSelector { get; set; }

        /// <summary>
        /// Equinix assigned URI of the stream subscription resource
        /// </summary>
        [Input("href")]
        public Input<string>? Href { get; set; }

        /// <summary>
        /// Lists of metrics to be included/excluded on the stream subscription
        /// </summary>
        [Input("metricSelector")]
        public Input<Inputs.StreamSubscriptionMetricSelectorGetArgs>? MetricSelector { get; set; }

        /// <summary>
        /// Customer-provided stream subscription name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The details of the subscriber to the Equinix Stream
        /// </summary>
        [Input("sink")]
        public Input<Inputs.StreamSubscriptionSinkGetArgs>? Sink { get; set; }

        /// <summary>
        /// Value representing provisioning status for the stream resource
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        /// <summary>
        /// The uuid of the stream that is the target of the stream subscription
        /// </summary>
        [Input("streamId")]
        public Input<string>? StreamId { get; set; }

        [Input("timeouts")]
        public Input<Inputs.StreamSubscriptionTimeoutsGetArgs>? Timeouts { get; set; }

        /// <summary>
        /// Type of the stream subscription request
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Equinix assigned unique identifier of the stream subscription resource
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        public StreamSubscriptionState()
        {
        }
        public static new StreamSubscriptionState Empty => new StreamSubscriptionState();
    }
}
