// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.fabric.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetPortEncapsulation {
    private String tagProtocolId;
    private String type;

    private GetPortEncapsulation() {}
    public String tagProtocolId() {
        return this.tagProtocolId;
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPortEncapsulation defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String tagProtocolId;
        private String type;
        public Builder() {}
        public Builder(GetPortEncapsulation defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.tagProtocolId = defaults.tagProtocolId;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder tagProtocolId(String tagProtocolId) {
            this.tagProtocolId = Objects.requireNonNull(tagProtocolId);
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public GetPortEncapsulation build() {
            final var o = new GetPortEncapsulation();
            o.tagProtocolId = tagProtocolId;
            o.type = type;
            return o;
        }
    }
}
