// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.fabric.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCloudRoutersDataPackage {
    /**
     * @return Fabric Cloud Router package code
     * 
     */
    private String code;

    private GetCloudRoutersDataPackage() {}
    /**
     * @return Fabric Cloud Router package code
     * 
     */
    public String code() {
        return this.code;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCloudRoutersDataPackage defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String code;
        public Builder() {}
        public Builder(GetCloudRoutersDataPackage defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.code = defaults.code;
        }

        @CustomType.Setter
        public Builder code(String code) {
            if (code == null) {
              throw new MissingRequiredPropertyException("GetCloudRoutersDataPackage", "code");
            }
            this.code = code;
            return this;
        }
        public GetCloudRoutersDataPackage build() {
            final var _resultValue = new GetCloudRoutersDataPackage();
            _resultValue.code = code;
            return _resultValue;
        }
    }
}
