// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.fabric.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCloudRouterMarketplaceSubscription {
    /**
     * @return Marketplace Subscription type like; AWS_MARKETPLACE_SUBSCRIPTION
     * 
     */
    private String type;
    /**
     * @return Equinix-assigned Marketplace Subscription identifier
     * 
     */
    private String uuid;

    private GetCloudRouterMarketplaceSubscription() {}
    /**
     * @return Marketplace Subscription type like; AWS_MARKETPLACE_SUBSCRIPTION
     * 
     */
    public String type() {
        return this.type;
    }
    /**
     * @return Equinix-assigned Marketplace Subscription identifier
     * 
     */
    public String uuid() {
        return this.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCloudRouterMarketplaceSubscription defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String type;
        private String uuid;
        public Builder() {}
        public Builder(GetCloudRouterMarketplaceSubscription defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.type = defaults.type;
    	      this.uuid = defaults.uuid;
        }

        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetCloudRouterMarketplaceSubscription", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder uuid(String uuid) {
            if (uuid == null) {
              throw new MissingRequiredPropertyException("GetCloudRouterMarketplaceSubscription", "uuid");
            }
            this.uuid = uuid;
            return this;
        }
        public GetCloudRouterMarketplaceSubscription build() {
            final var _resultValue = new GetCloudRouterMarketplaceSubscription();
            _resultValue.type = type;
            _resultValue.uuid = uuid;
            return _resultValue;
        }
    }
}
