// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.fabric.outputs;

import com.equinix.pulumi.equinix.fabric.outputs.GetPrecisionTimeServicePrecisionTimePriceCharge;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetPrecisionTimeServicePrecisionTimePrice {
    /**
     * @return offering price charge
     * 
     */
    private List<GetPrecisionTimeServicePrecisionTimePriceCharge> charges;
    /**
     * @return Offering price currency
     * 
     */
    private String currency;

    private GetPrecisionTimeServicePrecisionTimePrice() {}
    /**
     * @return offering price charge
     * 
     */
    public List<GetPrecisionTimeServicePrecisionTimePriceCharge> charges() {
        return this.charges;
    }
    /**
     * @return Offering price currency
     * 
     */
    public String currency() {
        return this.currency;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPrecisionTimeServicePrecisionTimePrice defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetPrecisionTimeServicePrecisionTimePriceCharge> charges;
        private String currency;
        public Builder() {}
        public Builder(GetPrecisionTimeServicePrecisionTimePrice defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.charges = defaults.charges;
    	      this.currency = defaults.currency;
        }

        @CustomType.Setter
        public Builder charges(List<GetPrecisionTimeServicePrecisionTimePriceCharge> charges) {
            if (charges == null) {
              throw new MissingRequiredPropertyException("GetPrecisionTimeServicePrecisionTimePrice", "charges");
            }
            this.charges = charges;
            return this;
        }
        public Builder charges(GetPrecisionTimeServicePrecisionTimePriceCharge... charges) {
            return charges(List.of(charges));
        }
        @CustomType.Setter
        public Builder currency(String currency) {
            if (currency == null) {
              throw new MissingRequiredPropertyException("GetPrecisionTimeServicePrecisionTimePrice", "currency");
            }
            this.currency = currency;
            return this;
        }
        public GetPrecisionTimeServicePrecisionTimePrice build() {
            final var _resultValue = new GetPrecisionTimeServicePrecisionTimePrice();
            _resultValue.charges = charges;
            _resultValue.currency = currency;
            return _resultValue;
        }
    }
}
