// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.fabric.outputs;

import com.equinix.pulumi.equinix.fabric.outputs.ServiceTokenServiceTokenConnectionASideAccessPointSelectorInterface;
import com.equinix.pulumi.equinix.fabric.outputs.ServiceTokenServiceTokenConnectionASideAccessPointSelectorLinkProtocol;
import com.equinix.pulumi.equinix.fabric.outputs.ServiceTokenServiceTokenConnectionASideAccessPointSelectorNetwork;
import com.equinix.pulumi.equinix.fabric.outputs.ServiceTokenServiceTokenConnectionASideAccessPointSelectorPort;
import com.equinix.pulumi.equinix.fabric.outputs.ServiceTokenServiceTokenConnectionASideAccessPointSelectorVirtualDevice;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ServiceTokenServiceTokenConnectionASideAccessPointSelector {
    /**
     * @return Virtual Device Interface Configuration
     * 
     */
    private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorInterface interface_;
    /**
     * @return Link protocol Configuration
     * 
     */
    private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorLinkProtocol linkProtocol;
    /**
     * @return Network Configuration
     * 
     */
    private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorNetwork network;
    /**
     * @return Port Configuration
     * 
     */
    private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorPort port;
    /**
     * @return Type of Access point; COLO, VD, NETWORK
     * 
     */
    private @Nullable String type;
    /**
     * @return Virtual Device Configuration
     * 
     */
    private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorVirtualDevice virtualDevice;

    private ServiceTokenServiceTokenConnectionASideAccessPointSelector() {}
    /**
     * @return Virtual Device Interface Configuration
     * 
     */
    public Optional<ServiceTokenServiceTokenConnectionASideAccessPointSelectorInterface> interface_() {
        return Optional.ofNullable(this.interface_);
    }
    /**
     * @return Link protocol Configuration
     * 
     */
    public Optional<ServiceTokenServiceTokenConnectionASideAccessPointSelectorLinkProtocol> linkProtocol() {
        return Optional.ofNullable(this.linkProtocol);
    }
    /**
     * @return Network Configuration
     * 
     */
    public Optional<ServiceTokenServiceTokenConnectionASideAccessPointSelectorNetwork> network() {
        return Optional.ofNullable(this.network);
    }
    /**
     * @return Port Configuration
     * 
     */
    public Optional<ServiceTokenServiceTokenConnectionASideAccessPointSelectorPort> port() {
        return Optional.ofNullable(this.port);
    }
    /**
     * @return Type of Access point; COLO, VD, NETWORK
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }
    /**
     * @return Virtual Device Configuration
     * 
     */
    public Optional<ServiceTokenServiceTokenConnectionASideAccessPointSelectorVirtualDevice> virtualDevice() {
        return Optional.ofNullable(this.virtualDevice);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ServiceTokenServiceTokenConnectionASideAccessPointSelector defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorInterface interface_;
        private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorLinkProtocol linkProtocol;
        private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorNetwork network;
        private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorPort port;
        private @Nullable String type;
        private @Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorVirtualDevice virtualDevice;
        public Builder() {}
        public Builder(ServiceTokenServiceTokenConnectionASideAccessPointSelector defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.interface_ = defaults.interface_;
    	      this.linkProtocol = defaults.linkProtocol;
    	      this.network = defaults.network;
    	      this.port = defaults.port;
    	      this.type = defaults.type;
    	      this.virtualDevice = defaults.virtualDevice;
        }

        @CustomType.Setter("interface")
        public Builder interface_(@Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorInterface interface_) {

            this.interface_ = interface_;
            return this;
        }
        @CustomType.Setter
        public Builder linkProtocol(@Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorLinkProtocol linkProtocol) {

            this.linkProtocol = linkProtocol;
            return this;
        }
        @CustomType.Setter
        public Builder network(@Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorNetwork network) {

            this.network = network;
            return this;
        }
        @CustomType.Setter
        public Builder port(@Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorPort port) {

            this.port = port;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder virtualDevice(@Nullable ServiceTokenServiceTokenConnectionASideAccessPointSelectorVirtualDevice virtualDevice) {

            this.virtualDevice = virtualDevice;
            return this;
        }
        public ServiceTokenServiceTokenConnectionASideAccessPointSelector build() {
            final var _resultValue = new ServiceTokenServiceTokenConnectionASideAccessPointSelector();
            _resultValue.interface_ = interface_;
            _resultValue.linkProtocol = linkProtocol;
            _resultValue.network = network;
            _resultValue.port = port;
            _resultValue.type = type;
            _resultValue.virtualDevice = virtualDevice;
            return _resultValue;
        }
    }
}
