// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Fabric.Inputs
{

    public sealed class PortOrderSignatureGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// delegate order details
        /// </summary>
        [Input("delegate", required: true)]
        public Input<Inputs.PortOrderSignatureDelegateGetArgs> Delegate { get; set; } = null!;

        /// <summary>
        /// Port signature Type
        /// </summary>
        [Input("signatory", required: true)]
        public Input<string> Signatory { get; set; } = null!;

        public PortOrderSignatureGetArgs()
        {
        }
        public static new PortOrderSignatureGetArgs Empty => new PortOrderSignatureGetArgs();
    }
}
