// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Fabric.Inputs
{

    public sealed class ServiceProfileCustomFieldGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required field
        /// </summary>
        [Input("captureInEmail")]
        public Input<bool>? CaptureInEmail { get; set; }

        /// <summary>
        /// Data type
        /// </summary>
        [Input("dataType", required: true)]
        public Input<string> DataType { get; set; } = null!;

        /// <summary>
        /// Description
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Label
        /// </summary>
        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        [Input("options")]
        private InputList<string>? _options;

        /// <summary>
        /// Options
        /// </summary>
        public InputList<string> Options
        {
            get => _options ?? (_options = new InputList<string>());
            set => _options = value;
        }

        /// <summary>
        /// Required field
        /// </summary>
        [Input("required", required: true)]
        public Input<bool> Required { get; set; } = null!;

        public ServiceProfileCustomFieldGetArgs()
        {
        }
        public static new ServiceProfileCustomFieldGetArgs Empty => new ServiceProfileCustomFieldGetArgs();
    }
}
