// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.NetworkEdge.Outputs
{

    [OutputType]
    public sealed class DeviceClusterDetailsNode0
    {
        /// <summary>
        /// Identifier of a license file that will be applied on the device.
        /// </summary>
        public readonly string? LicenseFileId;
        /// <summary>
        /// License Token applicable for some device types in BYOL licensing
        /// mode.
        /// </summary>
        public readonly string? LicenseToken;
        /// <summary>
        /// Device name.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Device unique identifier.
        /// </summary>
        public readonly string? Uuid;
        /// <summary>
        /// Map of vendor specific configuration parameters for a device
        /// (controller1, activationKey, managementType, siteId, systemIpAddress)
        /// * `ssh-key` - (Optional) Definition of SSH key that will be provisioned
        /// on a device (max one key).  See SSH Key below for more details.
        /// </summary>
        public readonly Outputs.DeviceClusterDetailsNode0VendorConfiguration? VendorConfiguration;

        [OutputConstructor]
        private DeviceClusterDetailsNode0(
            string? licenseFileId,

            string? licenseToken,

            string? name,

            string? uuid,

            Outputs.DeviceClusterDetailsNode0VendorConfiguration? vendorConfiguration)
        {
            LicenseFileId = licenseFileId;
            LicenseToken = licenseToken;
            Name = name;
            Uuid = uuid;
            VendorConfiguration = vendorConfiguration;
        }
    }
}
