// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.fabric.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetRoutingProtocolBfd extends com.pulumi.resources.InvokeArgs {

    public static final GetRoutingProtocolBfd Empty = new GetRoutingProtocolBfd();

    /**
     * Bidirectional Forwarding Detection enablement
     * 
     */
    @Import(name="enabled", required=true)
    private Boolean enabled;

    /**
     * @return Bidirectional Forwarding Detection enablement
     * 
     */
    public Boolean enabled() {
        return this.enabled;
    }

    /**
     * Interval range between the received BFD control packets
     * 
     */
    @Import(name="interval")
    private @Nullable String interval;

    /**
     * @return Interval range between the received BFD control packets
     * 
     */
    public Optional<String> interval() {
        return Optional.ofNullable(this.interval);
    }

    private GetRoutingProtocolBfd() {}

    private GetRoutingProtocolBfd(GetRoutingProtocolBfd $) {
        this.enabled = $.enabled;
        this.interval = $.interval;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRoutingProtocolBfd defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRoutingProtocolBfd $;

        public Builder() {
            $ = new GetRoutingProtocolBfd();
        }

        public Builder(GetRoutingProtocolBfd defaults) {
            $ = new GetRoutingProtocolBfd(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Bidirectional Forwarding Detection enablement
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param interval Interval range between the received BFD control packets
         * 
         * @return builder
         * 
         */
        public Builder interval(@Nullable String interval) {
            $.interval = interval;
            return this;
        }

        public GetRoutingProtocolBfd build() {
            $.enabled = Objects.requireNonNull($.enabled, "expected parameter 'enabled' to be non-null");
            return $;
        }
    }

}
