// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.fabric.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetStreamAlertRuleDetectionMethodArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetStreamAlertRuleDetectionMethodArgs Empty = new GetStreamAlertRuleDetectionMethodArgs();

    /**
     * Stream alert rule metric critical threshold
     * 
     */
    @Import(name="criticalThreshold", required=true)
    private Output<String> criticalThreshold;

    /**
     * @return Stream alert rule metric critical threshold
     * 
     */
    public Output<String> criticalThreshold() {
        return this.criticalThreshold;
    }

    /**
     * Stream alert rule metric operand
     * 
     */
    @Import(name="operand", required=true)
    private Output<String> operand;

    /**
     * @return Stream alert rule metric operand
     * 
     */
    public Output<String> operand() {
        return this.operand;
    }

    /**
     * Stream Alert Rule detection method type
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return Stream Alert Rule detection method type
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     * Stream alert rule metric warning threshold
     * 
     */
    @Import(name="warningThreshold", required=true)
    private Output<String> warningThreshold;

    /**
     * @return Stream alert rule metric warning threshold
     * 
     */
    public Output<String> warningThreshold() {
        return this.warningThreshold;
    }

    /**
     * Stream alert rule metric window size
     * 
     */
    @Import(name="windowSize", required=true)
    private Output<String> windowSize;

    /**
     * @return Stream alert rule metric window size
     * 
     */
    public Output<String> windowSize() {
        return this.windowSize;
    }

    private GetStreamAlertRuleDetectionMethodArgs() {}

    private GetStreamAlertRuleDetectionMethodArgs(GetStreamAlertRuleDetectionMethodArgs $) {
        this.criticalThreshold = $.criticalThreshold;
        this.operand = $.operand;
        this.type = $.type;
        this.warningThreshold = $.warningThreshold;
        this.windowSize = $.windowSize;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetStreamAlertRuleDetectionMethodArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetStreamAlertRuleDetectionMethodArgs $;

        public Builder() {
            $ = new GetStreamAlertRuleDetectionMethodArgs();
        }

        public Builder(GetStreamAlertRuleDetectionMethodArgs defaults) {
            $ = new GetStreamAlertRuleDetectionMethodArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param criticalThreshold Stream alert rule metric critical threshold
         * 
         * @return builder
         * 
         */
        public Builder criticalThreshold(Output<String> criticalThreshold) {
            $.criticalThreshold = criticalThreshold;
            return this;
        }

        /**
         * @param criticalThreshold Stream alert rule metric critical threshold
         * 
         * @return builder
         * 
         */
        public Builder criticalThreshold(String criticalThreshold) {
            return criticalThreshold(Output.of(criticalThreshold));
        }

        /**
         * @param operand Stream alert rule metric operand
         * 
         * @return builder
         * 
         */
        public Builder operand(Output<String> operand) {
            $.operand = operand;
            return this;
        }

        /**
         * @param operand Stream alert rule metric operand
         * 
         * @return builder
         * 
         */
        public Builder operand(String operand) {
            return operand(Output.of(operand));
        }

        /**
         * @param type Stream Alert Rule detection method type
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Stream Alert Rule detection method type
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param warningThreshold Stream alert rule metric warning threshold
         * 
         * @return builder
         * 
         */
        public Builder warningThreshold(Output<String> warningThreshold) {
            $.warningThreshold = warningThreshold;
            return this;
        }

        /**
         * @param warningThreshold Stream alert rule metric warning threshold
         * 
         * @return builder
         * 
         */
        public Builder warningThreshold(String warningThreshold) {
            return warningThreshold(Output.of(warningThreshold));
        }

        /**
         * @param windowSize Stream alert rule metric window size
         * 
         * @return builder
         * 
         */
        public Builder windowSize(Output<String> windowSize) {
            $.windowSize = windowSize;
            return this;
        }

        /**
         * @param windowSize Stream alert rule metric window size
         * 
         * @return builder
         * 
         */
        public Builder windowSize(String windowSize) {
            return windowSize(Output.of(windowSize));
        }

        public GetStreamAlertRuleDetectionMethodArgs build() {
            if ($.criticalThreshold == null) {
                throw new MissingRequiredPropertyException("GetStreamAlertRuleDetectionMethodArgs", "criticalThreshold");
            }
            if ($.operand == null) {
                throw new MissingRequiredPropertyException("GetStreamAlertRuleDetectionMethodArgs", "operand");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("GetStreamAlertRuleDetectionMethodArgs", "type");
            }
            if ($.warningThreshold == null) {
                throw new MissingRequiredPropertyException("GetStreamAlertRuleDetectionMethodArgs", "warningThreshold");
            }
            if ($.windowSize == null) {
                throw new MissingRequiredPropertyException("GetStreamAlertRuleDetectionMethodArgs", "windowSize");
            }
            return $;
        }
    }

}
