// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.fabric.inputs;

import com.equinix.pulumi.fabric.inputs.PrecisionTimeServiceAccountArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServiceChangeLogArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServiceConnectionArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServiceIpv4Args;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServiceNtpAdvancedConfigurationArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServiceOperationArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServiceOrderArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServicePackageArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServicePrecisionTimePriceArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServiceProjectArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServicePtpAdvancedConfigurationArgs;
import com.equinix.pulumi.fabric.inputs.PrecisionTimeServiceTimeoutsArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PrecisionTimeServiceState extends com.pulumi.resources.ResourceArgs {

    public static final PrecisionTimeServiceState Empty = new PrecisionTimeServiceState();

    /**
     * Equinix User Account associated with Precision Time Service
     * 
     */
    @Import(name="account")
    private @Nullable Output<PrecisionTimeServiceAccountArgs> account;

    /**
     * @return Equinix User Account associated with Precision Time Service
     * 
     */
    public Optional<Output<PrecisionTimeServiceAccountArgs>> account() {
        return Optional.ofNullable(this.account);
    }

    /**
     * Details of the last change on the route aggregation resource
     * 
     */
    @Import(name="changeLog")
    private @Nullable Output<PrecisionTimeServiceChangeLogArgs> changeLog;

    /**
     * @return Details of the last change on the route aggregation resource
     * 
     */
    public Optional<Output<PrecisionTimeServiceChangeLogArgs>> changeLog() {
        return Optional.ofNullable(this.changeLog);
    }

    /**
     * An array of objects with unique identifiers of connections.
     * 
     */
    @Import(name="connections")
    private @Nullable Output<List<PrecisionTimeServiceConnectionArgs>> connections;

    /**
     * @return An array of objects with unique identifiers of connections.
     * 
     */
    public Optional<Output<List<PrecisionTimeServiceConnectionArgs>>> connections() {
        return Optional.ofNullable(this.connections);
    }

    /**
     * Equinix generated Portal link for the created Precision Time Service
     * 
     */
    @Import(name="href")
    private @Nullable Output<String> href;

    /**
     * @return Equinix generated Portal link for the created Precision Time Service
     * 
     */
    public Optional<Output<String>> href() {
        return Optional.ofNullable(this.href);
    }

    /**
     * An object that has Network IP Configurations for Timing Master Servers.
     * 
     */
    @Import(name="ipv4")
    private @Nullable Output<PrecisionTimeServiceIpv4Args> ipv4;

    /**
     * @return An object that has Network IP Configurations for Timing Master Servers.
     * 
     */
    public Optional<Output<PrecisionTimeServiceIpv4Args>> ipv4() {
        return Optional.ofNullable(this.ipv4);
    }

    /**
     * Name of Precision Time Service. Applicable values: Maximum: 24 characters; Allowed characters: alpha-numeric, hyphens (&#39;-&#39;) and underscores (&#39;_&#39;)
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of Precision Time Service. Applicable values: Maximum: 24 characters; Allowed characters: alpha-numeric, hyphens (&#39;-&#39;) and underscores (&#39;_&#39;)
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * NTP Advanced configuration
     * 
     */
    @Import(name="ntpAdvancedConfigurations")
    private @Nullable Output<List<PrecisionTimeServiceNtpAdvancedConfigurationArgs>> ntpAdvancedConfigurations;

    /**
     * @return NTP Advanced configuration
     * 
     */
    public Optional<Output<List<PrecisionTimeServiceNtpAdvancedConfigurationArgs>>> ntpAdvancedConfigurations() {
        return Optional.ofNullable(this.ntpAdvancedConfigurations);
    }

    /**
     * Precision Time Service Operation
     * 
     */
    @Import(name="operation")
    private @Nullable Output<PrecisionTimeServiceOperationArgs> operation;

    /**
     * @return Precision Time Service Operation
     * 
     */
    public Optional<Output<PrecisionTimeServiceOperationArgs>> operation() {
        return Optional.ofNullable(this.operation);
    }

    /**
     * Precision Time Order
     * 
     */
    @Import(name="order")
    private @Nullable Output<PrecisionTimeServiceOrderArgs> order;

    /**
     * @return Precision Time Order
     * 
     */
    public Optional<Output<PrecisionTimeServiceOrderArgs>> order() {
        return Optional.ofNullable(this.order);
    }

    /**
     * Precision Time Service Package Details
     * 
     */
    @Import(name="package")
    private @Nullable Output<PrecisionTimeServicePackageArgs> package_;

    /**
     * @return Precision Time Service Package Details
     * 
     */
    public Optional<Output<PrecisionTimeServicePackageArgs>> package_() {
        return Optional.ofNullable(this.package_);
    }

    /**
     * Precision Time Service Price
     * 
     */
    @Import(name="precisionTimePrice")
    private @Nullable Output<PrecisionTimeServicePrecisionTimePriceArgs> precisionTimePrice;

    /**
     * @return Precision Time Service Price
     * 
     */
    public Optional<Output<PrecisionTimeServicePrecisionTimePriceArgs>> precisionTimePrice() {
        return Optional.ofNullable(this.precisionTimePrice);
    }

    /**
     * Equinix Project attribute object
     * 
     */
    @Import(name="project")
    private @Nullable Output<PrecisionTimeServiceProjectArgs> project;

    /**
     * @return Equinix Project attribute object
     * 
     */
    public Optional<Output<PrecisionTimeServiceProjectArgs>> project() {
        return Optional.ofNullable(this.project);
    }

    /**
     * PTP Advanced Configuration
     * 
     */
    @Import(name="ptpAdvancedConfiguration")
    private @Nullable Output<PrecisionTimeServicePtpAdvancedConfigurationArgs> ptpAdvancedConfiguration;

    /**
     * @return PTP Advanced Configuration
     * 
     */
    public Optional<Output<PrecisionTimeServicePtpAdvancedConfigurationArgs>> ptpAdvancedConfiguration() {
        return Optional.ofNullable(this.ptpAdvancedConfiguration);
    }

    /**
     * Indicator of the state of this Precision Time Service
     * 
     */
    @Import(name="state")
    private @Nullable Output<String> state;

    /**
     * @return Indicator of the state of this Precision Time Service
     * 
     */
    public Optional<Output<String>> state() {
        return Optional.ofNullable(this.state);
    }

    @Import(name="timeouts")
    private @Nullable Output<PrecisionTimeServiceTimeoutsArgs> timeouts;

    public Optional<Output<PrecisionTimeServiceTimeoutsArgs>> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    /**
     * Choose type of Precision Time Service
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return Choose type of Precision Time Service
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * Equinix generated id for the Precision Time Service
     * 
     */
    @Import(name="uuid")
    private @Nullable Output<String> uuid;

    /**
     * @return Equinix generated id for the Precision Time Service
     * 
     */
    public Optional<Output<String>> uuid() {
        return Optional.ofNullable(this.uuid);
    }

    private PrecisionTimeServiceState() {}

    private PrecisionTimeServiceState(PrecisionTimeServiceState $) {
        this.account = $.account;
        this.changeLog = $.changeLog;
        this.connections = $.connections;
        this.href = $.href;
        this.ipv4 = $.ipv4;
        this.name = $.name;
        this.ntpAdvancedConfigurations = $.ntpAdvancedConfigurations;
        this.operation = $.operation;
        this.order = $.order;
        this.package_ = $.package_;
        this.precisionTimePrice = $.precisionTimePrice;
        this.project = $.project;
        this.ptpAdvancedConfiguration = $.ptpAdvancedConfiguration;
        this.state = $.state;
        this.timeouts = $.timeouts;
        this.type = $.type;
        this.uuid = $.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PrecisionTimeServiceState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PrecisionTimeServiceState $;

        public Builder() {
            $ = new PrecisionTimeServiceState();
        }

        public Builder(PrecisionTimeServiceState defaults) {
            $ = new PrecisionTimeServiceState(Objects.requireNonNull(defaults));
        }

        /**
         * @param account Equinix User Account associated with Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder account(@Nullable Output<PrecisionTimeServiceAccountArgs> account) {
            $.account = account;
            return this;
        }

        /**
         * @param account Equinix User Account associated with Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder account(PrecisionTimeServiceAccountArgs account) {
            return account(Output.of(account));
        }

        /**
         * @param changeLog Details of the last change on the route aggregation resource
         * 
         * @return builder
         * 
         */
        public Builder changeLog(@Nullable Output<PrecisionTimeServiceChangeLogArgs> changeLog) {
            $.changeLog = changeLog;
            return this;
        }

        /**
         * @param changeLog Details of the last change on the route aggregation resource
         * 
         * @return builder
         * 
         */
        public Builder changeLog(PrecisionTimeServiceChangeLogArgs changeLog) {
            return changeLog(Output.of(changeLog));
        }

        /**
         * @param connections An array of objects with unique identifiers of connections.
         * 
         * @return builder
         * 
         */
        public Builder connections(@Nullable Output<List<PrecisionTimeServiceConnectionArgs>> connections) {
            $.connections = connections;
            return this;
        }

        /**
         * @param connections An array of objects with unique identifiers of connections.
         * 
         * @return builder
         * 
         */
        public Builder connections(List<PrecisionTimeServiceConnectionArgs> connections) {
            return connections(Output.of(connections));
        }

        /**
         * @param connections An array of objects with unique identifiers of connections.
         * 
         * @return builder
         * 
         */
        public Builder connections(PrecisionTimeServiceConnectionArgs... connections) {
            return connections(List.of(connections));
        }

        /**
         * @param href Equinix generated Portal link for the created Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder href(@Nullable Output<String> href) {
            $.href = href;
            return this;
        }

        /**
         * @param href Equinix generated Portal link for the created Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder href(String href) {
            return href(Output.of(href));
        }

        /**
         * @param ipv4 An object that has Network IP Configurations for Timing Master Servers.
         * 
         * @return builder
         * 
         */
        public Builder ipv4(@Nullable Output<PrecisionTimeServiceIpv4Args> ipv4) {
            $.ipv4 = ipv4;
            return this;
        }

        /**
         * @param ipv4 An object that has Network IP Configurations for Timing Master Servers.
         * 
         * @return builder
         * 
         */
        public Builder ipv4(PrecisionTimeServiceIpv4Args ipv4) {
            return ipv4(Output.of(ipv4));
        }

        /**
         * @param name Name of Precision Time Service. Applicable values: Maximum: 24 characters; Allowed characters: alpha-numeric, hyphens (&#39;-&#39;) and underscores (&#39;_&#39;)
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of Precision Time Service. Applicable values: Maximum: 24 characters; Allowed characters: alpha-numeric, hyphens (&#39;-&#39;) and underscores (&#39;_&#39;)
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param ntpAdvancedConfigurations NTP Advanced configuration
         * 
         * @return builder
         * 
         */
        public Builder ntpAdvancedConfigurations(@Nullable Output<List<PrecisionTimeServiceNtpAdvancedConfigurationArgs>> ntpAdvancedConfigurations) {
            $.ntpAdvancedConfigurations = ntpAdvancedConfigurations;
            return this;
        }

        /**
         * @param ntpAdvancedConfigurations NTP Advanced configuration
         * 
         * @return builder
         * 
         */
        public Builder ntpAdvancedConfigurations(List<PrecisionTimeServiceNtpAdvancedConfigurationArgs> ntpAdvancedConfigurations) {
            return ntpAdvancedConfigurations(Output.of(ntpAdvancedConfigurations));
        }

        /**
         * @param ntpAdvancedConfigurations NTP Advanced configuration
         * 
         * @return builder
         * 
         */
        public Builder ntpAdvancedConfigurations(PrecisionTimeServiceNtpAdvancedConfigurationArgs... ntpAdvancedConfigurations) {
            return ntpAdvancedConfigurations(List.of(ntpAdvancedConfigurations));
        }

        /**
         * @param operation Precision Time Service Operation
         * 
         * @return builder
         * 
         */
        public Builder operation(@Nullable Output<PrecisionTimeServiceOperationArgs> operation) {
            $.operation = operation;
            return this;
        }

        /**
         * @param operation Precision Time Service Operation
         * 
         * @return builder
         * 
         */
        public Builder operation(PrecisionTimeServiceOperationArgs operation) {
            return operation(Output.of(operation));
        }

        /**
         * @param order Precision Time Order
         * 
         * @return builder
         * 
         */
        public Builder order(@Nullable Output<PrecisionTimeServiceOrderArgs> order) {
            $.order = order;
            return this;
        }

        /**
         * @param order Precision Time Order
         * 
         * @return builder
         * 
         */
        public Builder order(PrecisionTimeServiceOrderArgs order) {
            return order(Output.of(order));
        }

        /**
         * @param package_ Precision Time Service Package Details
         * 
         * @return builder
         * 
         */
        public Builder package_(@Nullable Output<PrecisionTimeServicePackageArgs> package_) {
            $.package_ = package_;
            return this;
        }

        /**
         * @param package_ Precision Time Service Package Details
         * 
         * @return builder
         * 
         */
        public Builder package_(PrecisionTimeServicePackageArgs package_) {
            return package_(Output.of(package_));
        }

        /**
         * @param precisionTimePrice Precision Time Service Price
         * 
         * @return builder
         * 
         */
        public Builder precisionTimePrice(@Nullable Output<PrecisionTimeServicePrecisionTimePriceArgs> precisionTimePrice) {
            $.precisionTimePrice = precisionTimePrice;
            return this;
        }

        /**
         * @param precisionTimePrice Precision Time Service Price
         * 
         * @return builder
         * 
         */
        public Builder precisionTimePrice(PrecisionTimeServicePrecisionTimePriceArgs precisionTimePrice) {
            return precisionTimePrice(Output.of(precisionTimePrice));
        }

        /**
         * @param project Equinix Project attribute object
         * 
         * @return builder
         * 
         */
        public Builder project(@Nullable Output<PrecisionTimeServiceProjectArgs> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project Equinix Project attribute object
         * 
         * @return builder
         * 
         */
        public Builder project(PrecisionTimeServiceProjectArgs project) {
            return project(Output.of(project));
        }

        /**
         * @param ptpAdvancedConfiguration PTP Advanced Configuration
         * 
         * @return builder
         * 
         */
        public Builder ptpAdvancedConfiguration(@Nullable Output<PrecisionTimeServicePtpAdvancedConfigurationArgs> ptpAdvancedConfiguration) {
            $.ptpAdvancedConfiguration = ptpAdvancedConfiguration;
            return this;
        }

        /**
         * @param ptpAdvancedConfiguration PTP Advanced Configuration
         * 
         * @return builder
         * 
         */
        public Builder ptpAdvancedConfiguration(PrecisionTimeServicePtpAdvancedConfigurationArgs ptpAdvancedConfiguration) {
            return ptpAdvancedConfiguration(Output.of(ptpAdvancedConfiguration));
        }

        /**
         * @param state Indicator of the state of this Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder state(@Nullable Output<String> state) {
            $.state = state;
            return this;
        }

        /**
         * @param state Indicator of the state of this Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder state(String state) {
            return state(Output.of(state));
        }

        public Builder timeouts(@Nullable Output<PrecisionTimeServiceTimeoutsArgs> timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public Builder timeouts(PrecisionTimeServiceTimeoutsArgs timeouts) {
            return timeouts(Output.of(timeouts));
        }

        /**
         * @param type Choose type of Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Choose type of Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param uuid Equinix generated id for the Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder uuid(@Nullable Output<String> uuid) {
            $.uuid = uuid;
            return this;
        }

        /**
         * @param uuid Equinix generated id for the Precision Time Service
         * 
         * @return builder
         * 
         */
        public Builder uuid(String uuid) {
            return uuid(Output.of(uuid));
        }

        public PrecisionTimeServiceState build() {
            return $;
        }
    }

}
