// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.fabric.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs Empty = new ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs();

    /**
     * Virtual Device Cluster Information
     * 
     */
    @Import(name="cluster")
    private @Nullable Output<String> cluster;

    /**
     * @return Virtual Device Cluster Information
     * 
     */
    public Optional<Output<String>> cluster() {
        return Optional.ofNullable(this.cluster);
    }

    /**
     * Unique Resource Identifier
     * 
     */
    @Import(name="href")
    private @Nullable Output<String> href;

    /**
     * @return Unique Resource Identifier
     * 
     */
    public Optional<Output<String>> href() {
        return Optional.ofNullable(this.href);
    }

    /**
     * Customer-assigned Virtual Device Name
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Customer-assigned Virtual Device Name
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Virtual Device type
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return Virtual Device type
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * Equinix-assigned Virtual Device identifier
     * 
     */
    @Import(name="uuid", required=true)
    private Output<String> uuid;

    /**
     * @return Equinix-assigned Virtual Device identifier
     * 
     */
    public Output<String> uuid() {
        return this.uuid;
    }

    private ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs() {}

    private ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs(ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs $) {
        this.cluster = $.cluster;
        this.href = $.href;
        this.name = $.name;
        this.type = $.type;
        this.uuid = $.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs $;

        public Builder() {
            $ = new ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs();
        }

        public Builder(ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs defaults) {
            $ = new ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cluster Virtual Device Cluster Information
         * 
         * @return builder
         * 
         */
        public Builder cluster(@Nullable Output<String> cluster) {
            $.cluster = cluster;
            return this;
        }

        /**
         * @param cluster Virtual Device Cluster Information
         * 
         * @return builder
         * 
         */
        public Builder cluster(String cluster) {
            return cluster(Output.of(cluster));
        }

        /**
         * @param href Unique Resource Identifier
         * 
         * @return builder
         * 
         */
        public Builder href(@Nullable Output<String> href) {
            $.href = href;
            return this;
        }

        /**
         * @param href Unique Resource Identifier
         * 
         * @return builder
         * 
         */
        public Builder href(String href) {
            return href(Output.of(href));
        }

        /**
         * @param name Customer-assigned Virtual Device Name
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Customer-assigned Virtual Device Name
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param type Virtual Device type
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Virtual Device type
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param uuid Equinix-assigned Virtual Device identifier
         * 
         * @return builder
         * 
         */
        public Builder uuid(Output<String> uuid) {
            $.uuid = uuid;
            return this;
        }

        /**
         * @param uuid Equinix-assigned Virtual Device identifier
         * 
         * @return builder
         * 
         */
        public Builder uuid(String uuid) {
            return uuid(Output.of(uuid));
        }

        public ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs build() {
            if ($.uuid == null) {
                throw new MissingRequiredPropertyException("ServiceTokenServiceTokenConnectionZSideAccessPointSelectorVirtualDeviceArgs", "uuid");
            }
            return $;
        }
    }

}
