// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Fabric.Outputs
{

    [OutputType]
    public sealed class GetConnectionZSideResult
    {
        public readonly ImmutableArray<Outputs.GetConnectionZSideAccessPointResult> AccessPoints;
        public readonly ImmutableArray<Outputs.GetConnectionZSideServiceTokenResult> ServiceTokens;

        [OutputConstructor]
        private GetConnectionZSideResult(
            ImmutableArray<Outputs.GetConnectionZSideAccessPointResult> accessPoints,

            ImmutableArray<Outputs.GetConnectionZSideServiceTokenResult> serviceTokens)
        {
            AccessPoints = accessPoints;
            ServiceTokens = serviceTokens;
        }
    }
}
