// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Fabric.Outputs
{

    [OutputType]
    public sealed class PortAccount
    {
        /// <summary>
        /// Legal name of the accountholder.
        /// </summary>
        public readonly string? AccountName;
        /// <summary>
        /// Account number the port will be created for
        /// </summary>
        public readonly int AccountNumber;
        /// <summary>
        /// Enterprise datastore id
        /// </summary>
        public readonly string? UcmId;

        [OutputConstructor]
        private PortAccount(
            string? accountName,

            int accountNumber,

            string? ucmId)
        {
            AccountName = accountName;
            AccountNumber = accountNumber;
            UcmId = ucmId;
        }
    }
}
