// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Equinix.Fabric.Outputs
{

    [OutputType]
    public sealed class StreamAlertRuleResourceSelector
    {
        /// <summary>
        /// List of metrics to include
        /// </summary>
        public readonly ImmutableArray<string> Includes;

        [OutputConstructor]
        private StreamAlertRuleResourceSelector(ImmutableArray<string> includes)
        {
            Includes = includes;
        }
    }
}
