// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.fabric.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConnectionOperationErrorAdditionalInfoArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConnectionOperationErrorAdditionalInfoArgs Empty = new ConnectionOperationErrorAdditionalInfoArgs();

    @Import(name="property")
    private @Nullable Output<String> property;

    public Optional<Output<String>> property() {
        return Optional.ofNullable(this.property);
    }

    @Import(name="reason")
    private @Nullable Output<String> reason;

    public Optional<Output<String>> reason() {
        return Optional.ofNullable(this.reason);
    }

    private ConnectionOperationErrorAdditionalInfoArgs() {}

    private ConnectionOperationErrorAdditionalInfoArgs(ConnectionOperationErrorAdditionalInfoArgs $) {
        this.property = $.property;
        this.reason = $.reason;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConnectionOperationErrorAdditionalInfoArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConnectionOperationErrorAdditionalInfoArgs $;

        public Builder() {
            $ = new ConnectionOperationErrorAdditionalInfoArgs();
        }

        public Builder(ConnectionOperationErrorAdditionalInfoArgs defaults) {
            $ = new ConnectionOperationErrorAdditionalInfoArgs(Objects.requireNonNull(defaults));
        }

        public Builder property(@Nullable Output<String> property) {
            $.property = property;
            return this;
        }

        public Builder property(String property) {
            return property(Output.of(property));
        }

        public Builder reason(@Nullable Output<String> reason) {
            $.reason = reason;
            return this;
        }

        public Builder reason(String reason) {
            return reason(Output.of(reason));
        }

        public ConnectionOperationErrorAdditionalInfoArgs build() {
            return $;
        }
    }

}
