// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.fabric.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRouteAggregationPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRouteAggregationPlainArgs Empty = new GetRouteAggregationPlainArgs();

    /**
     * The uuid of the route aggregation this data source should retrieve
     * 
     */
    @Import(name="routeAggregationId", required=true)
    private String routeAggregationId;

    /**
     * @return The uuid of the route aggregation this data source should retrieve
     * 
     */
    public String routeAggregationId() {
        return this.routeAggregationId;
    }

    private GetRouteAggregationPlainArgs() {}

    private GetRouteAggregationPlainArgs(GetRouteAggregationPlainArgs $) {
        this.routeAggregationId = $.routeAggregationId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRouteAggregationPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRouteAggregationPlainArgs $;

        public Builder() {
            $ = new GetRouteAggregationPlainArgs();
        }

        public Builder(GetRouteAggregationPlainArgs defaults) {
            $ = new GetRouteAggregationPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param routeAggregationId The uuid of the route aggregation this data source should retrieve
         * 
         * @return builder
         * 
         */
        public Builder routeAggregationId(String routeAggregationId) {
            $.routeAggregationId = routeAggregationId;
            return this;
        }

        public GetRouteAggregationPlainArgs build() {
            if ($.routeAggregationId == null) {
                throw new MissingRequiredPropertyException("GetRouteAggregationPlainArgs", "routeAggregationId");
            }
            return $;
        }
    }

}
