// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.fabric.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRoutingProtocolPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRoutingProtocolPlainArgs Empty = new GetRoutingProtocolPlainArgs();

    /**
     * Connection URI associated with Routing Protocol
     * 
     */
    @Import(name="connectionUuid", required=true)
    private String connectionUuid;

    /**
     * @return Connection URI associated with Routing Protocol
     * 
     */
    public String connectionUuid() {
        return this.connectionUuid;
    }

    /**
     * Equinix-assigned routing protocol identifier
     * 
     */
    @Import(name="uuid", required=true)
    private String uuid;

    /**
     * @return Equinix-assigned routing protocol identifier
     * 
     */
    public String uuid() {
        return this.uuid;
    }

    private GetRoutingProtocolPlainArgs() {}

    private GetRoutingProtocolPlainArgs(GetRoutingProtocolPlainArgs $) {
        this.connectionUuid = $.connectionUuid;
        this.uuid = $.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRoutingProtocolPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRoutingProtocolPlainArgs $;

        public Builder() {
            $ = new GetRoutingProtocolPlainArgs();
        }

        public Builder(GetRoutingProtocolPlainArgs defaults) {
            $ = new GetRoutingProtocolPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param connectionUuid Connection URI associated with Routing Protocol
         * 
         * @return builder
         * 
         */
        public Builder connectionUuid(String connectionUuid) {
            $.connectionUuid = connectionUuid;
            return this;
        }

        /**
         * @param uuid Equinix-assigned routing protocol identifier
         * 
         * @return builder
         * 
         */
        public Builder uuid(String uuid) {
            $.uuid = uuid;
            return this;
        }

        public GetRoutingProtocolPlainArgs build() {
            if ($.connectionUuid == null) {
                throw new MissingRequiredPropertyException("GetRoutingProtocolPlainArgs", "connectionUuid");
            }
            if ($.uuid == null) {
                throw new MissingRequiredPropertyException("GetRoutingProtocolPlainArgs", "uuid");
            }
            return $;
        }
    }

}
