// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.fabric.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetStreamSubscriptionArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetStreamSubscriptionArgs Empty = new GetStreamSubscriptionArgs();

    /**
     * The uuid of the stream that is the target of the stream subscription
     * 
     */
    @Import(name="streamId", required=true)
    private Output<String> streamId;

    /**
     * @return The uuid of the stream that is the target of the stream subscription
     * 
     */
    public Output<String> streamId() {
        return this.streamId;
    }

    /**
     * The uuid of the stream subscription
     * 
     */
    @Import(name="subscriptionId", required=true)
    private Output<String> subscriptionId;

    /**
     * @return The uuid of the stream subscription
     * 
     */
    public Output<String> subscriptionId() {
        return this.subscriptionId;
    }

    private GetStreamSubscriptionArgs() {}

    private GetStreamSubscriptionArgs(GetStreamSubscriptionArgs $) {
        this.streamId = $.streamId;
        this.subscriptionId = $.subscriptionId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetStreamSubscriptionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetStreamSubscriptionArgs $;

        public Builder() {
            $ = new GetStreamSubscriptionArgs();
        }

        public Builder(GetStreamSubscriptionArgs defaults) {
            $ = new GetStreamSubscriptionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param streamId The uuid of the stream that is the target of the stream subscription
         * 
         * @return builder
         * 
         */
        public Builder streamId(Output<String> streamId) {
            $.streamId = streamId;
            return this;
        }

        /**
         * @param streamId The uuid of the stream that is the target of the stream subscription
         * 
         * @return builder
         * 
         */
        public Builder streamId(String streamId) {
            return streamId(Output.of(streamId));
        }

        /**
         * @param subscriptionId The uuid of the stream subscription
         * 
         * @return builder
         * 
         */
        public Builder subscriptionId(Output<String> subscriptionId) {
            $.subscriptionId = subscriptionId;
            return this;
        }

        /**
         * @param subscriptionId The uuid of the stream subscription
         * 
         * @return builder
         * 
         */
        public Builder subscriptionId(String subscriptionId) {
            return subscriptionId(Output.of(subscriptionId));
        }

        public GetStreamSubscriptionArgs build() {
            if ($.streamId == null) {
                throw new MissingRequiredPropertyException("GetStreamSubscriptionArgs", "streamId");
            }
            if ($.subscriptionId == null) {
                throw new MissingRequiredPropertyException("GetStreamSubscriptionArgs", "subscriptionId");
            }
            return $;
        }
    }

}
