// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.fabric.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class StreamAlertRuleResourceSelectorArgs extends com.pulumi.resources.ResourceArgs {

    public static final StreamAlertRuleResourceSelectorArgs Empty = new StreamAlertRuleResourceSelectorArgs();

    /**
     * List of metrics to include
     * 
     */
    @Import(name="includes", required=true)
    private Output<List<String>> includes;

    /**
     * @return List of metrics to include
     * 
     */
    public Output<List<String>> includes() {
        return this.includes;
    }

    private StreamAlertRuleResourceSelectorArgs() {}

    private StreamAlertRuleResourceSelectorArgs(StreamAlertRuleResourceSelectorArgs $) {
        this.includes = $.includes;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(StreamAlertRuleResourceSelectorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private StreamAlertRuleResourceSelectorArgs $;

        public Builder() {
            $ = new StreamAlertRuleResourceSelectorArgs();
        }

        public Builder(StreamAlertRuleResourceSelectorArgs defaults) {
            $ = new StreamAlertRuleResourceSelectorArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param includes List of metrics to include
         * 
         * @return builder
         * 
         */
        public Builder includes(Output<List<String>> includes) {
            $.includes = includes;
            return this;
        }

        /**
         * @param includes List of metrics to include
         * 
         * @return builder
         * 
         */
        public Builder includes(List<String> includes) {
            return includes(Output.of(includes));
        }

        /**
         * @param includes List of metrics to include
         * 
         * @return builder
         * 
         */
        public Builder includes(String... includes) {
            return includes(List.of(includes));
        }

        public StreamAlertRuleResourceSelectorArgs build() {
            if ($.includes == null) {
                throw new MissingRequiredPropertyException("StreamAlertRuleResourceSelectorArgs", "includes");
            }
            return $;
        }
    }

}
