// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.equinix.metal;

import com.equinix.pulumi.equinix.Utilities;
import com.equinix.pulumi.equinix.metal.OrganizationArgs;
import com.equinix.pulumi.equinix.metal.inputs.OrganizationState;
import com.equinix.pulumi.equinix.metal.outputs.OrganizationAddress;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a resource to manage organization resource in Equinix Metal.
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.equinix.metal.Organization;
 * import com.pulumi.equinix.metal.OrganizationArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var tfOrganization1 = new Organization(&#34;tfOrganization1&#34;, OrganizationArgs.builder()        
 *             .description(&#34;quux&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 * ## Import
 * 
 * This resource can be imported using an existing organization ID
 * 
 * ```sh
 *  $ pulumi import equinix:metal/organization:Organization equinix_metal_organization {existing_organization_id}
 * ```
 * 
 */
@ResourceType(type="equinix:metal/organization:Organization")
public class Organization extends com.pulumi.resources.CustomResource {
    /**
     * An object that has the address information. See Address
     * below for more details.
     * 
     */
    @Export(name="address", refs={OrganizationAddress.class}, tree="[0]")
    private Output<OrganizationAddress> address;

    /**
     * @return An object that has the address information. See Address
     * below for more details.
     * 
     */
    public Output<OrganizationAddress> address() {
        return this.address;
    }
    /**
     * The timestamp for when the organization was created.
     * 
     */
    @Export(name="created", refs={String.class}, tree="[0]")
    private Output<String> created;

    /**
     * @return The timestamp for when the organization was created.
     * 
     */
    public Output<String> created() {
        return this.created;
    }
    /**
     * Description string.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Description string.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Logo URL.
     * 
     */
    @Export(name="logo", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> logo;

    /**
     * @return Logo URL.
     * 
     */
    public Output<Optional<String>> logo() {
        return Codegen.optional(this.logo);
    }
    /**
     * The name of the Organization.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the Organization.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Twitter handle.
     * 
     */
    @Export(name="twitter", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> twitter;

    /**
     * @return Twitter handle.
     * 
     */
    public Output<Optional<String>> twitter() {
        return Codegen.optional(this.twitter);
    }
    /**
     * The timestamp for the last time the organization was updated.
     * 
     */
    @Export(name="updated", refs={String.class}, tree="[0]")
    private Output<String> updated;

    /**
     * @return The timestamp for the last time the organization was updated.
     * 
     */
    public Output<String> updated() {
        return this.updated;
    }
    /**
     * Website link.
     * 
     */
    @Export(name="website", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> website;

    /**
     * @return Website link.
     * 
     */
    public Output<Optional<String>> website() {
        return Codegen.optional(this.website);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Organization(String name) {
        this(name, OrganizationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Organization(String name, OrganizationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Organization(String name, OrganizationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("equinix:metal/organization:Organization", name, args == null ? OrganizationArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Organization(String name, Output<String> id, @Nullable OrganizationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("equinix:metal/organization:Organization", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Organization get(String name, Output<String> id, @Nullable OrganizationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Organization(name, id, state, options);
    }
}
