# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetReceivedRoutesResult',
    'AwaitableGetReceivedRoutesResult',
    'get_received_routes',
    'get_received_routes_output',
]

@pulumi.output_type
class GetReceivedRoutesResult:
    """
    A collection of values returned by getReceivedRoutes.
    """
    def __init__(__self__, connection_id=None, datas=None, filter=None, id=None, pagination=None, sort=None):
        if connection_id and not isinstance(connection_id, str):
            raise TypeError("Expected argument 'connection_id' to be a str")
        pulumi.set(__self__, "connection_id", connection_id)
        if datas and not isinstance(datas, list):
            raise TypeError("Expected argument 'datas' to be a list")
        pulumi.set(__self__, "datas", datas)
        if filter and not isinstance(filter, dict):
            raise TypeError("Expected argument 'filter' to be a dict")
        pulumi.set(__self__, "filter", filter)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if pagination and not isinstance(pagination, dict):
            raise TypeError("Expected argument 'pagination' to be a dict")
        pulumi.set(__self__, "pagination", pagination)
        if sort and not isinstance(sort, dict):
            raise TypeError("Expected argument 'sort' to be a dict")
        pulumi.set(__self__, "sort", sort)

    @_builtins.property
    @pulumi.getter(name="connectionId")
    def connection_id(self) -> _builtins.str:
        """
        The uuid of the routes this data source should retrieve
        """
        return pulumi.get(self, "connection_id")

    @_builtins.property
    @pulumi.getter
    def datas(self) -> Sequence['outputs.GetReceivedRoutesDataResult']:
        """
        Returned list of received routes objects
        """
        return pulumi.get(self, "datas")

    @_builtins.property
    @pulumi.getter
    def filter(self) -> 'outputs.GetReceivedRoutesFilterResult':
        """
        Filters for the Data Source Search Request
        """
        return pulumi.get(self, "filter")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the resource
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def pagination(self) -> 'outputs.GetReceivedRoutesPaginationResult':
        """
        Pagination details for the returned received routes list
        """
        return pulumi.get(self, "pagination")

    @_builtins.property
    @pulumi.getter
    def sort(self) -> Optional['outputs.GetReceivedRoutesSortResult']:
        """
        Sort details for the returned received routes list
        """
        return pulumi.get(self, "sort")


class AwaitableGetReceivedRoutesResult(GetReceivedRoutesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetReceivedRoutesResult(
            connection_id=self.connection_id,
            datas=self.datas,
            filter=self.filter,
            id=self.id,
            pagination=self.pagination,
            sort=self.sort)


def get_received_routes(connection_id: Optional[_builtins.str] = None,
                        filter: Optional[Union['GetReceivedRoutesFilterArgs', 'GetReceivedRoutesFilterArgsDict', 'outputs.GetReceivedRoutesFilterResult']] = None,
                        pagination: Optional[Union['GetReceivedRoutesPaginationArgs', 'GetReceivedRoutesPaginationArgsDict', 'outputs.GetReceivedRoutesPaginationResult']] = None,
                        sort: Optional[Union['GetReceivedRoutesSortArgs', 'GetReceivedRoutesSortArgsDict', 'outputs.GetReceivedRoutesSortResult']] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetReceivedRoutesResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str connection_id: The uuid of the routes this data source should retrieve
    :param Union['GetReceivedRoutesFilterArgs', 'GetReceivedRoutesFilterArgsDict', 'outputs.GetReceivedRoutesFilterResult'] filter: Filters for the Data Source Search Request
    :param Union['GetReceivedRoutesPaginationArgs', 'GetReceivedRoutesPaginationArgsDict', 'outputs.GetReceivedRoutesPaginationResult'] pagination: Pagination details for the returned received routes list
    :param Union['GetReceivedRoutesSortArgs', 'GetReceivedRoutesSortArgsDict', 'outputs.GetReceivedRoutesSortResult'] sort: Sort details for the returned received routes list
    """
    __args__ = dict()
    __args__['connectionId'] = connection_id
    __args__['filter'] = filter
    __args__['pagination'] = pagination
    __args__['sort'] = sort
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('equinix:fabric/getReceivedRoutes:getReceivedRoutes', __args__, opts=opts, typ=GetReceivedRoutesResult).value

    return AwaitableGetReceivedRoutesResult(
        connection_id=pulumi.get(__ret__, 'connection_id'),
        datas=pulumi.get(__ret__, 'datas'),
        filter=pulumi.get(__ret__, 'filter'),
        id=pulumi.get(__ret__, 'id'),
        pagination=pulumi.get(__ret__, 'pagination'),
        sort=pulumi.get(__ret__, 'sort'))
def get_received_routes_output(connection_id: pulumi.Input[Optional[_builtins.str]] = None,
                               filter: pulumi.Input[Optional[Union['GetReceivedRoutesFilterArgs', 'GetReceivedRoutesFilterArgsDict', 'outputs.GetReceivedRoutesFilterResult']]] = None,
                               pagination: pulumi.Input[Optional[Union['GetReceivedRoutesPaginationArgs', 'GetReceivedRoutesPaginationArgsDict', 'outputs.GetReceivedRoutesPaginationResult']]] = None,
                               sort: pulumi.Input[Optional[Optional[Union['GetReceivedRoutesSortArgs', 'GetReceivedRoutesSortArgsDict', 'outputs.GetReceivedRoutesSortResult']]]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetReceivedRoutesResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str connection_id: The uuid of the routes this data source should retrieve
    :param Union['GetReceivedRoutesFilterArgs', 'GetReceivedRoutesFilterArgsDict', 'outputs.GetReceivedRoutesFilterResult'] filter: Filters for the Data Source Search Request
    :param Union['GetReceivedRoutesPaginationArgs', 'GetReceivedRoutesPaginationArgsDict', 'outputs.GetReceivedRoutesPaginationResult'] pagination: Pagination details for the returned received routes list
    :param Union['GetReceivedRoutesSortArgs', 'GetReceivedRoutesSortArgsDict', 'outputs.GetReceivedRoutesSortResult'] sort: Sort details for the returned received routes list
    """
    __args__ = dict()
    __args__['connectionId'] = connection_id
    __args__['filter'] = filter
    __args__['pagination'] = pagination
    __args__['sort'] = sort
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('equinix:fabric/getReceivedRoutes:getReceivedRoutes', __args__, opts=opts, typ=GetReceivedRoutesResult)
    return __ret__.apply(lambda __response__: GetReceivedRoutesResult(
        connection_id=pulumi.get(__response__, 'connection_id'),
        datas=pulumi.get(__response__, 'datas'),
        filter=pulumi.get(__response__, 'filter'),
        id=pulumi.get(__response__, 'id'),
        pagination=pulumi.get(__response__, 'pagination'),
        sort=pulumi.get(__response__, 'sort')))
