// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.equinix.pulumi.networkedge.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AclTemplateInboundRule {
    /**
     * @return Inbound rule description, up to 200 characters.
     * 
     */
    private @Nullable String description;
    /**
     * @return Inbound traffic destination ports. Allowed values are a comma separated list of ports, e.g., `20,22,23`, port range, e.g., `1023-1040` or word `any`.
     * 
     */
    private String dstPort;
    /**
     * @return Inbound traffic protocol. One of `IP`, `TCP`, `UDP`.
     * 
     */
    private String protocol;
    /**
     * @return Inbound rule sequence number
     * 
     */
    private @Nullable Integer sequenceNumber;
    /**
     * @return Inbound traffic source ports. Allowed values are a comma separated list of ports, e.g., `20,22,23`, port range, e.g., `1023-1040` or word `any`.
     * 
     */
    private String srcPort;
    /**
     * @return Inbound traffic source IP subnet in CIDR format.
     * 
     */
    private @Nullable String subnet;

    private AclTemplateInboundRule() {}
    /**
     * @return Inbound rule description, up to 200 characters.
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    /**
     * @return Inbound traffic destination ports. Allowed values are a comma separated list of ports, e.g., `20,22,23`, port range, e.g., `1023-1040` or word `any`.
     * 
     */
    public String dstPort() {
        return this.dstPort;
    }
    /**
     * @return Inbound traffic protocol. One of `IP`, `TCP`, `UDP`.
     * 
     */
    public String protocol() {
        return this.protocol;
    }
    /**
     * @return Inbound rule sequence number
     * 
     */
    public Optional<Integer> sequenceNumber() {
        return Optional.ofNullable(this.sequenceNumber);
    }
    /**
     * @return Inbound traffic source ports. Allowed values are a comma separated list of ports, e.g., `20,22,23`, port range, e.g., `1023-1040` or word `any`.
     * 
     */
    public String srcPort() {
        return this.srcPort;
    }
    /**
     * @return Inbound traffic source IP subnet in CIDR format.
     * 
     */
    public Optional<String> subnet() {
        return Optional.ofNullable(this.subnet);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AclTemplateInboundRule defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String description;
        private String dstPort;
        private String protocol;
        private @Nullable Integer sequenceNumber;
        private String srcPort;
        private @Nullable String subnet;
        public Builder() {}
        public Builder(AclTemplateInboundRule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.dstPort = defaults.dstPort;
    	      this.protocol = defaults.protocol;
    	      this.sequenceNumber = defaults.sequenceNumber;
    	      this.srcPort = defaults.srcPort;
    	      this.subnet = defaults.subnet;
        }

        @CustomType.Setter
        public Builder description(@Nullable String description) {

            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder dstPort(String dstPort) {
            if (dstPort == null) {
              throw new MissingRequiredPropertyException("AclTemplateInboundRule", "dstPort");
            }
            this.dstPort = dstPort;
            return this;
        }
        @CustomType.Setter
        public Builder protocol(String protocol) {
            if (protocol == null) {
              throw new MissingRequiredPropertyException("AclTemplateInboundRule", "protocol");
            }
            this.protocol = protocol;
            return this;
        }
        @CustomType.Setter
        public Builder sequenceNumber(@Nullable Integer sequenceNumber) {

            this.sequenceNumber = sequenceNumber;
            return this;
        }
        @CustomType.Setter
        public Builder srcPort(String srcPort) {
            if (srcPort == null) {
              throw new MissingRequiredPropertyException("AclTemplateInboundRule", "srcPort");
            }
            this.srcPort = srcPort;
            return this;
        }
        @CustomType.Setter
        public Builder subnet(@Nullable String subnet) {

            this.subnet = subnet;
            return this;
        }
        public AclTemplateInboundRule build() {
            final var _resultValue = new AclTemplateInboundRule();
            _resultValue.description = description;
            _resultValue.dstPort = dstPort;
            _resultValue.protocol = protocol;
            _resultValue.sequenceNumber = sequenceNumber;
            _resultValue.srcPort = srcPort;
            _resultValue.subnet = subnet;
            return _resultValue;
        }
    }
}
