# WARNING: This file was build based on https://github.com/pulumi/ci-mgmt
# but it is currently not in sync. Any update must be done manually

env:
  GH_TOKEN: ${{ secrets.EQUINIX_BOT_TOKEN }}
jobs:
  check_upgrade_provider:
    name: Check for upstream provider upgrades
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup tools
      uses: ./.github/actions/setup-tools
      with:
        tools: go
    - name: Install upgrade-provider
      run: go install github.com/pulumi/upgrade-provider@ec62fc8d980f # NOTE: newer upgrade-provider versions do not initialize the upstream submodule
      shell: bash
    - name: "Set up git identity: name"
      run: git config --global user.name GitHub
      shell: bash
    - name: "Set up git identity: email"
      run: git config --global user.email noreply@github.com
      shell: bash
    - name: Run upgrade-provider upstream check
      id: upstream_version
      run: |
        upgrade-provider "$REPO" --kind=check-upstream-version
      env:
        REPO: ${{ github.repository }}
      shell: bash
name: Check upstream upgrade
on:
  workflow_dispatch: {} #so we can run this manually if necessary
  schedule:
    # Run every 8 hours Monday through Friday
    - cron: '0 */8 * * 1-5'
