# WARNING: This file was build based on https://github.com/pulumi/ci-mgmt
# but it is currently not in sync. Any update must be done manually

name: Upgrade provider
on:
  issues:
    types:
    - opened
  workflow_dispatch: {}
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  upgrade_provider:
    if: ${{ contains(github.event.issue.title, 'Upgrade terraform-provider-') || github.event_name == 'workflow_dispatch' }}
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@v0.0.12
      with:
        kind: all
        email: noreply@github.com
        username: GitHub
    ## TODO
    # - env:
    #     SLACK_CHANNEL: provider-upgrade-publish-status
    #     SLACK_COLOR: "#7CFC00"
    #     SLACK_ICON_EMOJI: ":taco:"
    #     SLACK_MESSAGE: >-
    #       Upgrade succeeded :heart_decoration:

    #       PR opened at github.com/pulumi/${{ github.event.repository.name }}/pulls
    #     SLACK_TITLE: ${{ github.event.repository.name }} upgrade result
    #     SLACK_USERNAME: provider-bot
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    #   name: Send Upgrade Success To Slack
    #   uses: rtCamp/action-slack-notify@v2
    # - env:
    #     SLACK_CHANNEL: provider-upgrade-publish-status
    #     SLACK_COLOR: "#FF0000"
    #     SLACK_ICON_EMOJI: ":taco:"
    #     SLACK_MESSAGE: " Upgrade failed :x:"
    #     SLACK_TITLE: ${{ github.event.repository.name }} upgrade result
    #     SLACK_USERNAME: provider-bot
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    #   if: failure()
    #   name: Send Upgrade Failure To Slack
    #   uses: rtCamp/action-slack-notify@v2
