# WARNING: This file was build based on https://github.com/pulumi/ci-mgmt
# but it is currently not in sync. Any update must be done manually

name: Upgrade provider
on:
  issues:
    types:
    - opened
  workflow_dispatch: {}

env:
  GH_TOKEN: ${{ secrets.EQUINIX_BOT_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Allow missing or extra mappings during TF provider
  # upgrades.  This allows automation to do its job so
  # that human contributions can be narrowly focused on
  # adding or removing resource mappings
  PULUMI_SKIP_MISSING_MAPPING_ERROR: true
  PULUMI_SKIP_EXTRA_MAPPING_ERROR: true
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Capture current pulumi-java version
      id: pulumi-java
      run: |
        echo "version=$(cat .pulumi-java-gen.version)" >> "$GITHUB_OUTPUT"
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@v0.0.12
      with:
        kind: provider
        email: noreply@github.com
        username: GitHub
        pr-title-prefix: "feat: "
        target-java-version: ${{ steps.pulumi-java.outputs.version }}
