# WARNING: This file was build based on https://github.com/pulumi/ci-mgmt
# but it is currently not in sync. Any update must be done manually

name: Upgrade bridge
on:
  repository_dispatch:
    types:
      - upgrade-bridge
  workflow_dispatch:
    inputs:
      target-bridge-version:
        description: pulumi-terraform-bridge version or hash reference
        required: false
        type: string
        default: "latest"
      pr-reviewers:
        description: Reviewers to assign to the auto-opened pull request
        required: false
        type: string
        default: ""
      pr-description:
        description: Extra description to add to the auto-opened pull request
        required: false
        type: string
        default: ""
      automerge:
        description: Mark created PR for auto-merging?
        required: false
        type: boolean
        default: false
env:
  GH_TOKEN: ${{ secrets.EQUINIX_BOT_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Call upgrade provider action
      if: github.event_name == 'workflow_dispatch'
      uses: equinix-labs/pulumi-upgrade-provider-action@parameterize-go-version
      #TODO: switch back to upstream when it supports configurable go version
      #uses: pulumi/pulumi-upgrade-provider-action@v0.0.12
      with:
        kind: bridge
        email: noreply@github.com
        username: GitHub
        automerge: ${{ inputs.automerge }}
        target-bridge-version: ${{ inputs.target-bridge-version }}
        pr-reviewers: ${{ inputs.pr-reviewers }}
        pr-description: ${{ inputs.pr-description }}
        pr-title-prefix: "feat: "
        go-version-file: provider/go.mod
    - name: Call upgrade provider action
      if: github.event_name == 'repository_dispatch'
      uses: equinix-labs/pulumi-upgrade-provider-action@parameterize-go-version
      #TODO: switch back to upstream when it supports configurable go version
      #uses: pulumi/pulumi-upgrade-provider-action@v0.0.12
      with:
        kind: bridge
        email: noreply@github.com
        username: GitHub
        automerge: ${{ github.event.client_payload.automerge }}
        target-bridge-version: ${{ github.event.client_payload.target-bridge-version }}
        pr-reviewers: ${{ github.event.client_payload.pr-reviewers }}
        pr-description: ${{ github.event.client_payload.pr-description }}
        go-version-file: provider/go.mod
